# -*- coding: utf-8 -*-
"""kbar_plotting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGtjHPM9PDd8NZbzgKAULuTMNB635NjT
"""

! pip install FinMind==1.5.4

import FinMind
from FinMind.data import DataLoader
from FinMind import plotting
print(FinMind.__version__)

stock_id = '2603'
start_date = '2018-01-01'
end_date = '2021-11-01'

data_loader = DataLoader()
stock_data = data_loader.taiwan_stock_daily(stock_id, start_date, end_date)
stock_data = data_loader.feature.add_kline_institutional_investors(
    stock_data
)
stock_data = data_loader.feature.add_kline_margin_purchase_short_sale(
    stock_data
)
# 繪製k線圖
kline_plot = plotting.kline(stock_data)

